/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourHuntRouteImport } from './routes/your-hunt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as HuntsRouteImport } from './routes/hunts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlayTokenRouteImport } from './routes/play.$token'
import { Route as HuntsSlugRouteImport } from './routes/hunts.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as StaffCloseTokenRouteImport } from './routes/staff.close.$token'

const YourHuntRoute = YourHuntRouteImport.update({
  id: '/your-hunt',
  path: '/your-hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsRoute = HuntsRouteImport.update({
  id: '/hunts',
  path: '/hunts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PlayTokenRoute = PlayTokenRouteImport.update({
  id: '/play/$token',
  path: '/play/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsSlugRoute = HuntsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HuntsRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCloseTokenRoute = StaffCloseTokenRouteImport.update({
  id: '/staff/close/$token',
  path: '/staff/close/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/hunts': typeof HuntsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/your-hunt': typeof YourHuntRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/hunts/$slug': typeof HuntsSlugRoute
  '/play/$token': typeof PlayTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/close/$token': typeof StaffCloseTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/hunts': typeof HuntsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/your-hunt': typeof YourHuntRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/hunts/$slug': typeof HuntsSlugRoute
  '/play/$token': typeof PlayTokenRoute
  '/admin': typeof AdminIndexRoute
  '/staff/close/$token': typeof StaffCloseTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/hunts': typeof HuntsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/your-hunt': typeof YourHuntRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/hunts/$slug': typeof HuntsSlugRoute
  '/play/$token': typeof PlayTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/close/$token': typeof StaffCloseTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/artists'
    | '/contact'
    | '/hunts'
    | '/reviews'
    | '/your-hunt'
    | '/api/stripe-webhook'
    | '/checkout/$slug'
    | '/checkout/success'
    | '/hunts/$slug'
    | '/play/$token'
    | '/admin/'
    | '/staff/close/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artists'
    | '/contact'
    | '/hunts'
    | '/reviews'
    | '/your-hunt'
    | '/api/stripe-webhook'
    | '/checkout/$slug'
    | '/checkout/success'
    | '/hunts/$slug'
    | '/play/$token'
    | '/admin'
    | '/staff/close/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/artists'
    | '/contact'
    | '/hunts'
    | '/reviews'
    | '/your-hunt'
    | '/api/stripe-webhook'
    | '/checkout/$slug'
    | '/checkout/success'
    | '/hunts/$slug'
    | '/play/$token'
    | '/admin/'
    | '/staff/close/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRoute
  ContactRoute: typeof ContactRoute
  HuntsRoute: typeof HuntsRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  YourHuntRoute: typeof YourHuntRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PlayTokenRoute: typeof PlayTokenRoute
  StaffCloseTokenRoute: typeof StaffCloseTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-hunt': {
      id: '/your-hunt'
      path: '/your-hunt'
      fullPath: '/your-hunt'
      preLoaderRoute: typeof YourHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts': {
      id: '/hunts'
      path: '/hunts'
      fullPath: '/hunts'
      preLoaderRoute: typeof HuntsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/play/$token': {
      id: '/play/$token'
      path: '/play/$token'
      fullPath: '/play/$token'
      preLoaderRoute: typeof PlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$slug': {
      id: '/hunts/$slug'
      path: '/$slug'
      fullPath: '/hunts/$slug'
      preLoaderRoute: typeof HuntsSlugRouteImport
      parentRoute: typeof HuntsRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/close/$token': {
      id: '/staff/close/$token'
      path: '/staff/close/$token'
      fullPath: '/staff/close/$token'
      preLoaderRoute: typeof StaffCloseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface HuntsRouteChildren {
  HuntsSlugRoute: typeof HuntsSlugRoute
}

const HuntsRouteChildren: HuntsRouteChildren = {
  HuntsSlugRoute: HuntsSlugRoute,
}

const HuntsRouteWithChildren = HuntsRoute._addFileChildren(HuntsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRoute,
  ContactRoute: ContactRoute,
  HuntsRoute: HuntsRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  YourHuntRoute: YourHuntRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PlayTokenRoute: PlayTokenRoute,
  StaffCloseTokenRoute: StaffCloseTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
